feat: Dodanie możliwości zapisywania preferencji wyświetlania strony przez użytkownika
typeofweb/polskifrontend pull request #115
Opened 2021-01-06 18:47 UTC by wisnie

Resolves #108

2021-01-07 16:17 UTC, AdamSiekierski commented on hooks/ useDisplayPreferences.tsx
> +      void router.replace(path, undefined, { shallow: false });
AFAIR nie trzeba mu mówić żeby nie było shallow, bo tak jest domyślnie

```suggestion
      void router.replace(path);
```

2021-01-07 16:17 UTC, AdamSiekierski commented on hooks/ useDisplayPreferences.tsx
> +      const path = `/${display}/${rest.join('/')}`;
Nie lepiej to regeksem?

2021-01-07 19:14 UTC, mmiszy requested changes
Wymaga zmian, o których rozmawialiśmy na Discordzie

2021-01-09 15:17 UTC, mmiszy approved these changes

2021-01-09 15:18 UTC, merged