feat: Dodano wyszukiwarkę Algolia do strony
typeofweb/polskifrontend pull request #124
Opened 2021-01-11 12:19 UTC by wisnie

Resolves #106

2021-01-11 13:39 UTC, mmiszy requested changes

2021-01-11 13:39 UTC, mmiszy commented on components/AlgoliaSearch/AlgoliaSearch.tsx
> +  process.env.ALGOLIA_API_SECRET as string,
Nazwy zmiennych środowiskowych na froncie muszą zaczynać się od NEXT_PUBLIC_

2021-01-11 13:39 UTC, mmiszy commented on components/AlgoliaSearch/AlgoliaSearch.tsx
> +  <div style={{ padding: '1rem', marginTop: '3rem' }}>
Klasa css? :P

2021-01-11 13:39 UTC, mmiszy commented on components/MainTiles/MainTiles.tsx
> +      <AlogliaSearch />
Włóżmy to w diva o stałej wysokości i załadujmy ten komponent dynamicznie z ssr:false, żeby na dzień dobry nie ładować całego algoliasearch

2021-01-11 13:40 UTC, mmiszy commented
@TypeofWebBot stats

2021-01-12 19:40 UTC, mmiszy commented
Działa, ale chyba nie wyświetla się tak, jakbyśmy tego chcieli ;)

2021-01-15 22:08 UTC, AdamSiekierski commented on components/AlgoliaSearch/AlgoliaSearch.tsx
> +  };
To chowanie, tak jak pisaliśmy na Discordzie, jest do dopracowania. Eventy które moga schować, to IMO powinny być:
- Kliknięcie poza wynikami searcha
- Wyczyszczenie inputa
- Może kliknięcie `esc` na klawiaturze 🤔

2021-01-15 22:08 UTC, AdamSiekierski commented on components/MainTiles/mainTiles.module.scss
> +  height: 5rem;
hmm

2021-01-15 22:08 UTC, AdamSiekierski commented on components/AlgoliaSearch/AlgoliaHit.tsx
> +};
Musimy ręcznie tworzyć ten typ?

2021-01-15 22:42 UTC, mmiszy commented on components/AlgoliaSearch/AlgoliaHits.tsx
> +  <ol className={styles.list}>
A co innego?

2021-01-16 08:46 UTC, AdamSiekierski commented on components/AlgoliaSearch/AlgoliaHits.tsx
> +  <ol className={styles.list}>
Nie jest wyświetlane nic świadczące o kolejności, chyba powinna być unordered list

2021-01-16 08:48 UTC, AdamSiekierski commented on components/AlgoliaSearch/AlgoliaHits.tsx
> +  <ol className={styles.list}>
Z drugiej strony o kolejności może świadczyć podobieństwo do wyszukiwanej frazy 🤔

2021-01-16 12:38 UTC, wisnie commented on components/MainTiles/mainTiles.module.scss
> +  height: 5rem;
Ładujemy ten komponent z dynamic, więc go nie ma na początku.

2021-01-16 12:42 UTC, wisnie commented on components/AlgoliaSearch/AlgoliaHit.tsx
> +};
Tak.

2021-01-16 20:25 UTC, AdamSiekierski commented on components/AlgoliaSearch/AlgoliaSearch.tsx
> +  const timeoutId = useRef<NodeJS.Timeout | null>(null);
wtf

```suggestion
  const timeoutId = useRef<ReturnType<setTimeout> | null>(null);

2021-01-16 20:27 UTC, AdamSiekierski commented on components/AlgoliaSearch/AlgoliaSearch.tsx
> +  const timeoutId = useRef<NodeJS.Timeout | null>(null);
a w rzeczywistości jest to po prostu `number` 😄

2021-01-19 12:11 UTC, mmiszy approved these changes

2021-01-20 12:24 UTC, merged