Add MainTiles component and new icons
typeofweb/polskifrontend pull request #24
Opened 2020-12-18 21:20 UTC by wisnie

2020-12-18 21:20 UTC, mmiszy commented
#### 📝Changed routes:


| [**/**](https://polskifrontend-biqoynfmj.vercel.app/) |
|:-:|
|<a href="https://polskifrontend-biqoynfmj.vercel.app/"><img src="https://images.weserv.nl?url=https://s.microlink.io/iShMiWCp8Xjbh7KFFAoTptJ5_WY_.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/3wsxtz1RsgROMBtERmK__sgvei4_.png">(view full size)</a> |







Commit ba11f307408e56ac9b41bbe473119389b0a491fa (https://polskifrontend-biqoynfmj.vercel.app).

2020-12-19 13:57 UTC, mmiszy requested changes

2020-12-19 13:57 UTC, mmiszy commented on components/MainTiles/MainTiles.tsx
> +          <button
Stworzyłbym komponent Button, który przyjmie propsy `as` (`button` albo `a`) oraz `icon` (nazwa ikony lub brak).

2020-12-19 13:57 UTC, mmiszy commented on components/MainTiles/mainTiles.module.scss
> +    padding: 15px 30px;
```suggestion
    padding: 1rem 2rem;
```

2020-12-19 13:57 UTC, mmiszy commented on components/MainTiles/mainTiles.module.scss
> +    background-color: #fff;
Wszystkie kolory do zmiennych w global.scss

2020-12-19 13:57 UTC, mmiszy commented on components/MainTiles/mainTiles.module.scss
> +  font-weight: bold;
```suggestion
  font-weight: 700;
```

2020-12-19 13:57 UTC, mmiszy commented on components/MainTiles/mainTiles.module.scss
> +  padding: 11.25px;
```suggestion
  padding: 0.7rem;
```

2020-12-19 13:57 UTC, mmiszy commented on components/MainTiles/mainTiles.module.scss
> +  padding: 30px 0 15px;
```suggestion
  padding: 2rem 0 1rem;
```

2020-12-19 13:57 UTC, mmiszy commented on components/MainTiles/mainTiles.module.scss
> +  max-width: 1170px;
```suggestion
  max-width: 73rem;
```

2020-12-19 13:57 UTC, mmiszy commented on components/MainTiles/mainTiles.module.scss
> +  font-size: 20px;
```suggestion
  font-size: 1.25rem;
```

2020-12-19 18:25 UTC, mmiszy commented on components/Button/Button.tsx
> +import React from 'react';
Be gone

2020-12-19 18:25 UTC, mmiszy commented on components/MainTiles/MainTiles.tsx
> +          <Button
Buttony nie mogą być puste, powinny mieć treść w spanie z klasą sr-only

2020-12-19 19:02 UTC, AdamSiekierski commented on components/Button/Button.tsx
> +import React from 'react';
akysz

2020-12-19 20:19 UTC, mmiszy commented on components/Button/button.module.scss
> +    background-color: #ffffff;
Zmienne css

2020-12-19 20:19 UTC, mmiszy commented on components/Button/button.module.scss
> +  &:nth-child(2) {
Why tho

2020-12-19 20:19 UTC, mmiszy commented on components/MainTiles/MainTiles.tsx
> +        <Link href="/zglos-serwis">
W takiej sytuacji chyba musimy passHref dać

2020-12-19 20:19 UTC, mmiszy commented on global.scss
> +  --brand-color-button: #10c982;
Zróbmy to tym samym zielonym co wyżej

2020-12-19 22:33 UTC, AdamSiekierski commented on components/Button/Button.tsx
> +  forwardRef<any, ButtonProps>(({ as: As = 'button', icon, children, onClick, disabled }, ref) => {
Dlaczego `any`?

2020-12-19 22:33 UTC, AdamSiekierski commented on components/MainTiles/MainTiles.tsx
> +        <Link href="/zglos-serwis">
Zgadza się, podbijam

2020-12-20 11:59 UTC, wisnie commented on components/Button/Button.tsx
> +  forwardRef<any, ButtonProps>(({ as: As = 'button', icon, children, onClick, disabled }, ref) => {
Trzeba dać `any`, albo ustawić // @ts-ignore, żeby nie podkreślało błędu przy ref.

2020-12-20 12:14 UTC, wisnie commented on components/DisplayStyleSwitch/DisplayStyleSwitch.tsx
> +      <input
Jeśli input jest w labelu, to nie możemy za pomocą pseudoclass w inpucie jak `input:checked` zmodyfikować stylów labela.

2020-12-20 12:18 UTC, mmiszy commented on components/DisplayStyleSwitch/DisplayStyleSwitch.tsx
> +      <input
Ale możemy spana, nie?

2020-12-20 12:19 UTC, wisnie commented on components/DisplayStyleSwitch/DisplayStyleSwitch.tsx
> +      <input
Można to też rozwiązać za pomocą JS, co może być bardziej czytelne.

2020-12-20 12:22 UTC, wisnie commented on components/DisplayStyleSwitch/DisplayStyleSwitch.tsx
> +      <input
Możemy spana, zaraz poprawię.

2020-12-20 13:52 UTC, mmiszy approved these changes

2020-12-20 13:52 UTC, merged