Create blogs grid
typeofweb/polskifrontend pull request #40
Opened 2020-12-23 17:34 UTC by AdamSiekierski

- Create a blogs grid using CSS Grid

Preview:
![image](https://user-images.githubusercontent.com/24841038/103023004-61c48700-454d-11eb-8b5d-051d9801c2f9.png)

Fixes #12

2020-12-23 17:39 UTC, mmiszy requested changes

2020-12-23 17:39 UTC, mmiszy commented on components/MainTiles/BlogsGrid.tsx
> +        <Fragment key={blog.id}>
Po co ten fragment?

2020-12-23 17:39 UTC, mmiszy commented on components/MainTiles/BlogsGrid.tsx
> +          {blog.articles.map((article) => (
Poprzednia struktura była dobra. Ta jest niesemantyczna. Czemu blog ma być na tej samej liście co jego artykuły? Artykuły powinny być w środku poprzedniego li tak, jak było.

2020-12-23 17:39 UTC, mmiszy commented on components/MainTiles/blogsGrid.module.scss
> +    .gridItem:nth-child(12n + #{$i}) {
Co tu się wydarzyło?

2020-12-23 17:52 UTC, wisnie commented on components/MainTiles/blogsGrid.module.scss
> +  }
Zamieniłbym te deklaracje kolejnością, najlepiej się czyta jak zaczynasz od najmniejszych wartości.

2020-12-23 17:58 UTC, wisnie commented on components/MainTiles/blogsGrid.module.scss
> +}
Może się tutaj czepiam, ale lubię stosować `Declaration Sorting`. Wtedy odrazu wiadomo, gdzie co jest w stylach.
https://sass-guidelin.es/

2020-12-23 20:39 UTC, mmiszy commented on components/MainTiles/BlogsGrid.tsx
> +              {' ' + blog.name}
🤔 Czemu ta spacja ma służyć?

2020-12-23 21:03 UTC, AdamSiekierski commented on components/MainTiles/BlogsGrid.tsx
> +              {' ' + blog.name}
🤔 🤔 🤔

2020-12-23 21:34 UTC, mmiszy submitted a review, later dismissed

2020-12-23 22:45 UTC, mmiszy requested changes

2020-12-23 22:45 UTC, mmiszy commented on components/Button/Button.tsx
> +  readonly iconPosition?: 'right' | 'left';
```suggestion
  readonly iconPosition: 'right' | 'left';
```

2020-12-23 22:45 UTC, mmiszy commented on components/Button/Button.tsx
> +    ({ as: As = 'button', icon, children, className = '', iconPosition, ...props }, ref) => {
```suggestion
    ({ as: As = 'button', icon, children, className = '', iconPosition = 'left', ...props }, ref) => {
```

2020-12-24 10:53 UTC, mmiszy approved these changes

2020-12-24 10:53 UTC, merged