feat: Dodano możliwość autoryzacji użytkowników
typeofweb/polskifrontend pull request #83
Opened 2020-12-29 21:24 UTC by wisnie

Dzięki za pracę nad Polski Frontend!

Pamiętaj, aby PR-owi nadać tytuł w języku polskim i zgodny z _Conventional Commits_. Przykłady znajdziesz tutaj: https://highlab.pl/conventional-commits/

Dzięki!

Resolves #123123123

2020-12-29 23:34 UTC, mmiszy requested changes

2020-12-29 23:34 UTC, mmiszy commented on api-helpers/prisma/schema.prisma
>  model Session {
https://next-auth.js.org/schemas/models#session

> It is not used if JSON Web Tokens are enabled.

2020-12-29 23:34 UTC, mmiszy commented on pages/api/auth/[...nextauth].ts
> +};
Musimy chyba dodać tutaj session callback żeby dodać do tokenu jwt rolę użytkownika:
https://next-auth.js.org/configuration/callbacks#session-callback

2020-12-30 09:19 UTC, AdamSiekierski commented on components/Loading/Loading.module.css
> +  transform: translate(-50%, -50%) rotate(360deg);
Moożna tak, ale da się to zrobić lepiej :)

2020-12-30 09:19 UTC, AdamSiekierski commented on pages/api/auth/[...nextauth].ts
> +const authHandler: NextApiHandler = (req, res) => NextAuth(req, res, options);
Tutaj musisz nawiązać połączenie z bazą danych przez `openConnection`, i wtedy podać instancję Prismy jako adapter ;)

2020-12-30 09:19 UTC, AdamSiekierski commented on api-helpers/prisma/schema.prisma
> +  userId             Int       @map(name: "user_id")
To nie jest tak że poleciał cały model Usera?

2020-12-30 09:54 UTC, wisnie commented on .env-sample
> +SECRET="hmmmmmm"
Używam tego jako `secret` w options `next-auth`, więc według dokumentacji `A random string used to hash tokens, sign cookies and generate crytographic keys.` jeśli dobrze rozumiem, nie jest to JWT, dalej w dokumentacji jest przykład z użyciem JWT_SECRET https://next-auth.js.org/configuration/options#jwt-helper

2020-12-30 10:02 UTC, wisnie commented on .env-sample
> +SECRET="hmmmmmm"
Chociaż chyba to jednak jest JWT_TOKEN.

2020-12-30 10:51 UTC, mmiszy commented on api-helpers/prisma/schema.prisma
> +  userId             Int       @map(name: "user_id")
co?

2020-12-30 15:20 UTC, mmiszy requested changes

2020-12-31 09:41 UTC, wisnie commented
Przenosimy tego taska na inny PR, ze względu na problemy z migracją bazy danych.

2020-12-31 09:41 UTC, closed without merging